---
swagger: "2.0"
info:
  description: "The REST services for annotation,
  notation, types, HLA, GFE, typing, feature and db releases"
  version: "0.1.0"
  title: "GFE REST Services"
  contact:
    email: "cibmtr-pypi@nmdp.org"
  license:
    name: "GNU Lesser General Public License version 3"
    url: "https://opensource.org/licenses/lgpl-3.0.html"
tags:
  - name: "GFE Sequence Annotation"
    description: "Return annotation by sequence"
  - name: "GFE Features Of Gene"
    description: "Return all features associated with a gene"
  - name: "HLA By GFE"
    description: "Return HLA annotation by GFE"
  - name: "KIR By GFE"
    description: "Return KIR annotation by GFE"
 
paths:

  /gfe/seq/annotate/{gene}:
    post:
      tags:
        - "GFE Sequence Annotation"
      operationId: "gfeAnnotation_post"
      consumes:
        - "application/json"
      parameters:
        - name: "gene"
          in: "path"
          description: "HUGO gene name"
          required: true
          type: "boolean"
        - in: 'body'
          name: 'sequence'
          required: true
          description: 'add the sequence to get the result'
          schema:
            type: 'object'
            required:
              - 'sequence'
            properties:
              sequence:
                type: 'string'
      responses:
        200:
          description: 'OK'
          schema:
            $ref: "#/definitions/Annotation"
        404:
          description: "Failed to annotate the sequence"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "api.controllers.gfe_annotation_controller"

  /gfe/features/{gene}:
    get:
      tags:
        - "GFE Features Of Gene"
      operationId: "genefeature_get"
      produces:
        - "application/json"
      parameters:
        - name: "gene"
          in: "path"
          description: "string containing HUGO gene"
          required: true
          type: "string"
      responses:
        200:
          description: "OK"
        404:
          description: "Failed to load the features of gene"
      x-swagger-router-controller: "api.controllers.gene_feature_controller"

  
  /gfe/hla/{gfe}:
    get:
      tags:
        - "HLA By GFE"
      operationId: "findhla_get"
      consumes:
        - "application/json"
      parameters:
        - name: "gfe"
          in: "path"
          description: "Valid GFE "
          required: true
          type: "string"
      responses:
        200:
          description: "OK"
        404:
          description: "Failed to get HLA from GFE"
      x-swagger-router-controller: "api.controllers.find_hla_controller"
      
  /gfe/kir/{gfe}:
    get:
      tags:
        - "KIR By GFE"
      operationId: "findkir_get"
      consumes:
        - "application/json"
      parameters:
        - name: "gfe"
          in: "path"
          description: "Valid GFE "
          required: true
          type: "string"
      responses:
        200:
          description: "OK"
        404:
          description: "Failed to get KIR from GFE"
      x-swagger-router-controller: "api.controllers.find_kir_controller"


definitions:
  Error:
    type: "object"
    required:
      - "Message"
      - "gfedb_version"
      - "imgtdb_version"
      - "pygfe_version"
    properties:
      Message:
        type: "string"
      pygfe_version:
        type: "string"
      gfedb_version:
        type: "string"
      imgtdb_version:
        type: "string"
      log:
        type: "array"
        items:
          type: "string"
      type:
        type: "string"
  Annotation:
    type: "object"
    properties:
      seqdiff:
        type: "array"
        items:
          $ref: "#/definitions/Seqdiff"
      protdiff:
        type: "array"
        items:
          $ref: "#/definitions/Seqdiff"
      features:
        type: "array"
        items:
          $ref: "#/definitions/Feature"
      novel_features:
        type: "array"
        items:
          $ref: "#/definitions/Feature"
      gfe:
        type: "string"
      differences:
        type: "integer"
      status:
        type: "string"
      pygfe_version:
        type: "string"
      gfedb_version:
        type: "string"
      imgtdb_version:
        type: "string"
    example:
      gfe: "HLA-Aw1-1-7-20-10-32-7-1-1-1-6-1-5-3-5-1-1"
      hla: "HLA-A*01:01:01:01"
      G: "HLA-A*01:01:01G"
      lg: "HLA-A*01:01g"
      differences: 10
      sequence_differences:
        - term: "intron"
          rank: 1
          pos: 10
          ref: "A"
          inseq: "G"
      protdiff:
        pos: 4
        location: "ARD"
        ref: "A"
        inseq: "G"
      status: "novel"
      features:
        - accession: 1
          gene: "HLA-A"
          rank: 1
          term: "exon"
          sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
        - accession: 2
          gene: "HLA-A"
          rank: 1
          sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
          term: "exon"
      act_version: "0.0.1"
      gfe_version: "0.0.1"
      gfedb_version: "0.0.1"
  Seqdiff:
    type: "object"
    properties:
      term:
        type: "string"
      rank:
        type: "integer"
      location:
        type: "integer"
      ref:
        type: "string"
      inseq:
        type: "string"
    example:
      term: "intron"
      rank: 1
      pos: 10
      ref: "A"
      inseq: "G"
  Feature:
    type: "object"
    properties:
      accession:
        type: "integer"
      rank:
        type: "integer"
      sequence:
        type: "string"
      term:
        type: "string"
    example:
      accession: 1
      gene: "HLA-A"
      rank: 1
      sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
      term: "exon"
